name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Rust-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1.2.1

      - name: Install dependencies
        run: |
          rustup update

      - name: Run tests
        run: cargo test --verbose

      - name: Build Release
        run: cargo build --release

      - name: Package with Cargo
        run: |
          cargo package

      - name: Archive the package
        id: get_package_info
        run: |
          PACKAGE_NAME=$(grep '^name = ' Cargo.toml | sed -E 's/^name = "(.*)"/\1/')
          PACKAGE_VERSION=$(grep '^version = ' Cargo.toml | sed -E 's/^version = "(.*)"/\1/')
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "Package Name: $PACKAGE_NAME"
          echo "Package Version: $PACKAGE_VERSION"
          PACKAGE_DIR="target/package/${PACKAGE_NAME}-${PACKAGE_VERSION}"
          tar -czvf "${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz" -C ./target/package/${PACKAGE_NAME}-${PACKAGE_VERSION}/

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz"
          path: "${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz"

      # - name: Build Docker image
      #   run: |
      #     docker build -t rust-app .

      # - name: Push Docker image to Docker Hub (optional)
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker tag rust-app ${{ secrets.DOCKER_USERNAME }}/rust-app:latest
      #     docker push ${{ secrets.DOCKER_USERNAME }}/rust-app:latest

      # - name: Clean up Docker images
      #   run: docker system prune -f
